// Matières du programme scolaire français, par niveau (même liste que
// l'espace famille, apps/famille/src/pages/curriculum.js).
export const SUBJECTS_BY_LEVEL = {
  primaire: [
    'Français',
    'Mathématiques',
    'Questionner le monde',
    'Histoire-Géographie',
    'Anglais',
    'Arts plastiques',
    'Éducation musicale',
    'EPS',
    'Éducation morale et civique',
  ],
  college: [
    'Français',
    'Mathématiques',
    'Histoire-Géographie',
    'Sciences de la Vie et de la Terre (SVT)',
    'Physique-Chimie',
    'Technologie',
    'Anglais',
    'Espagnol',
    'Allemand',
    'Latin',
    'Arts plastiques',
    'Éducation musicale',
    'EPS',
  ],
  lycee: [
    'Français',
    'Philosophie',
    'Mathématiques',
    'Histoire-Géographie',
    'Enseignement scientifique',
    'Anglais',
    'Espagnol',
    'Allemand',
    'SVT',
    'Physique-Chimie',
    'SES',
    'Numérique et Sciences Informatiques (NSI)',
    'Histoire-Géo, Géopolitique et Sciences Politiques',
    'Humanités, Littérature et Philosophie',
    'Langues, Littératures et Cultures Étrangères',
    'Sciences de l\'Ingénieur',
    'Arts',
    'EPS',
  ],
}
