import {
  Building2,
  Contact2,
  Globe,
  GraduationCap,
  Inbox,
  LayoutDashboard,
  LayoutList,
  LifeBuoy,
  MessageSquare,
  RadioTower,
  ShieldCheck,
  UserPlus,
  Users,
} from 'lucide-react'

export const NAV_ITEMS = [
  { label: 'Tableau de bord', path: '/', roles: ['super_admin', 'admin'], icon: LayoutDashboard },
  { label: 'Leads', path: '/leads', roles: ['super_admin', 'admin'], icon: Inbox },
  { label: 'Élèves', path: '/eleves', roles: ['super_admin', 'admin'], icon: Users },
  { label: 'Enseignants', path: '/enseignants', roles: ['super_admin', 'admin'], icon: Contact2 },
  {
    label: 'Demandes de professeur',
    path: '/demandes-professeur',
    roles: ['super_admin', 'admin'],
    icon: UserPlus,
  },
  {
    label: 'Candidatures',
    path: '/recrutement',
    roles: ['super_admin', 'admin', 'recruiter'],
    icon: GraduationCap,
  },
  {
    label: 'Conversations',
    path: '/conversations',
    roles: ['super_admin', 'admin'],
    icon: MessageSquare,
  },
  {
    label: 'Suivi des pointages',
    path: '/pointages',
    roles: ['super_admin', 'admin'],
    icon: RadioTower,
  },
  {
    label: 'Support',
    path: '/support-tickets',
    roles: ['super_admin', 'admin'],
    icon: LifeBuoy,
  },
  {
    label: 'Entreprises',
    path: '/entreprises',
    roles: ['super_admin', 'admin'],
    icon: Building2,
  },
  {
    label: 'Formules',
    path: '/formules',
    roles: ['super_admin', 'admin'],
    icon: LayoutList,
  },
  {
    label: 'Site vitrine',
    path: '/site-vitrine',
    roles: ['super_admin', 'admin'],
    icon: Globe,
  },
  { label: 'Comptes admin', path: '/comptes', roles: ['super_admin'], icon: ShieldCheck },
]
