-- Pass Éducatif — carte visuelle (identifiant séquentiel + classe précise)

ALTER TABLE students ADD COLUMN classe TEXT;

-- Compteur séquentiel pour l'identifiant affiché sur le Pass (NAF-{année}-{6 chiffres}).
-- GENERATED BY DEFAULT (pas ALWAYS) : Prisma insère toujours sans valeur explicite
-- ici, mais BY DEFAULT reste plus flexible si un backfill manuel est un jour requis.
ALTER TABLE students ADD COLUMN sequence_number INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE students ADD CONSTRAINT students_sequence_number_key UNIQUE (sequence_number);
