ALTER TABLE student_teachers ADD COLUMN IF NOT EXISTS hourly_rate DOUBLE PRECISION;
ALTER TABLE matchings ADD COLUMN IF NOT EXISTS hourly_rate DOUBLE PRECISION;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS hourly_rate DOUBLE PRECISION;
