ALTER TABLE teachers ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS availability_days TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE teacher_applications ADD COLUMN IF NOT EXISTS city TEXT;
