ALTER TABLE sessions ADD COLUMN IF NOT EXISTS chapter TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS topics TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS understanding INTEGER;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS participation INTEGER;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS difficulties TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS homework TEXT;
